### ISSUE TITLE
Questions about training data preparation

### ISSUE THREAD

**Issue by jokerhcy** [nobukatsu-kajiura/UR-COD#1]
Thanks to the author for sharing in COD tasks. I encountered a detailed problem in the process of Paper recurrence: What do Images_Gray specifically refer to in ./data/TrainDataset/Img_Gray/ for the preparation of training? It has not been mentioned in this papers.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/77950995/144740166-b610e533-d03d-4526-9881-71fae2744f55.png">

**Comment by nobukatsu-kajiura** [comment]
Thanks for your question.
This implementation refers to UCNet[1] and the smoothness loss used in this model requires a gray-scale image.
[1]  Zhang et al. UC-Net: Uncertainty Inspired RGB-D Saliency Detection via Conditional Variational Autoencoders. In CVPR. 2020.
